services:
  customer-postgres:
    image: postgres:18.4
    container_name: customer-postgres
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - customers-data:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d customers -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  customer-service:
    image: jmerce-customer-service:0.0.1
    container_name: customer-service
    environment:
      SERVER_PORT: 8090
      THC_PATH: /actuator/health
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-postgres:5432/customers
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "/workspace/health-check"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      customer-postgres:
        condition: service_healthy

volumes:
  customers-data:
