<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
    </parent>

    <groupId>by.raddan</groupId>
    <artifactId>jmerce-parent</artifactId>
    <packaging>pom</packaging>
    <version>0.0.1</version>

    <modules>
        <module>jmerce-customer-service</module>
    </modules>

    <properties>
        <!-- General Settings -->
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- JaCoCo Settings -->
        <jacoco.plugin.version>0.8.15</jacoco.plugin.version>
        <jacoco.branch.coverage.minimum>0.70</jacoco.branch.coverage.minimum>

        <!-- Other Settings -->
        <sql.formatter.version>2.0.5</sql.formatter.version>
        <datasource.proxy.version>2.0.1</datasource.proxy.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- SQL Logging -->
            <dependency>
                <groupId>com.github.gavlyukovskiy</groupId>
                <artifactId>datasource-proxy-spring-boot-starter</artifactId>
                <version>${datasource.proxy.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.github.vertical-blank</groupId>
                <artifactId>sql-formatter</artifactId>
                <version>${sql.formatter.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- Code Coverage -->
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.plugin.version}</version>
                    <executions>
                        <!-- Attach JaCoCo Agent Before Tests -->
                        <execution>
                            <id>jacoco-prepare-agent</id>
                            <phase>initialize</phase>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>

                        <!-- Generate Coverage Report -->
                        <execution>
                            <id>jacoco-report</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>report</goal>
                            </goals>
                        </execution>

                        <!-- Enforce Coverage Threshold -->
                        <execution>
                            <id>jacoco-check</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <rule>
                                        <element>BUNDLE</element>
                                        <limits>
                                            <limit>
                                                <counter>BRANCH</counter>
                                                <value>COVEREDRATIO</value>
                                                <minimum>${jacoco.branch.coverage.minimum}</minimum>
                                            </limit>
                                        </limits>
                                    </rule>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
